### PR TITLE
Property display

### PR DESCRIPTION
**Pull request by Ohmnivore**
Inspired by the property display feature in https://github.com/deepnight/led

image

image

## Features
- Choose between Hidden, Value Only, Name And Value display options for each entity value
- Each value type is displayed in a user-friendly manner (ex: disabled bool type is crossed-out)
- Global toggle button (screen bottom left) & shortcut (Ctrl-T)
- Font size scales with zoom and text fades out when zoom < 100%
- White font with black outline guarantees readability on all backgrounds

## Implementation
There were a few options I could see for text rendering:

1. Using WebGL + an external library (mesh font, bitmap font, or SDF, etc)
2. Using HTML5 canvas overlay
3. Using HTML/CSS overlay

Option 1 felt heavy-weight and I was concerned about full language support so I crossed it off. It's also most likely less performant and supports less features than options 2 and 3.

I chose option 3 over 2 for the simplicity of layout and styling using HTML/CSS. I also believe it's more performant (text rendering is done only when text content changes vs every frame). This approach can also more easily support user interaction and complex UI elements (for future stuff should we need them).

However it adds some friction that option 2 doesn't because it's retained-mode UI vs the rest of Ogmo level rendering which is immediate-mode UI. But I believe it's worth it,

The final result is overall an alternative HTML/CSS "render path" for elements (like text) that are better handled by the browser stack than WebGL. The FloatingHTML class is generic and can support stuff beyond text in the future.

## Possible improvements
- Font size control (in project settings?)
- More global enable/disable settings for the feature (ex: per-layer? show only for current layer?)
- Avoid overlap of property displays between neighboring entities (by nudging or changing alignment?)
- Looking for feedback and ideas

### CODE REVIEW

**Comment by 01010111** [comment]
this looks and feels good to me!

**Comment by 01010111** [comment]
this is working well for me!

**Comment by 01010111** [comment]
> More global enable/disable settings for the feature (ex: per-layer? show only for current layer?)
would it be possible to add this before we merge? At the very least I'd start with no settings and only show for the current layer?

**Comment by Ohmnivore** [comment]
image

Added this popup! Open/close with the T-looking icon in the bottom left corner. There's tooltips on hover that describe each field.

The values are saved per-user in the settings JSON file like so;

```json
{
  "recentProjects": [
    {"path": "C:\\Users\\Anon\\Desktop\\HAXEDEV\\OgmoEditor3-CE-temp\\tilemeta.ogmo", "name": "TileMeta"}
  ],
  "openLevelLimit": 30,
  "undoLimit": 100,
  "propertyDisplay": {"visible": true, "mode": 1, "fontSize": 0.9, "minimumZoom": 0.75},
...etc
```

**Pull request merged**
