### PR TITLE
Upgrade to Electron 12

### PR DESCRIPTION
**Pull request by superamadeus**
Issue: #111 

I upgraded electron to 12.0.4 (latest version on haxelib). I addressed immediate build errors as well as all breaking api changes I could find between 4 and 12, as noted here: https://www.electronjs.org/docs/breaking-changes

Honestly, I was surprised that it went so smoothly. I've tested basic functionality (macOS) and haven't run into any issues. But with such a major upgrade, I think it would be awesome if anyone else could test it out as well. 

Building and testing is the same, just make sure to use electron 12.0.4 (as noted in the updated README). 
Also, don't forget to re-run `npm install` since those dependencies have been upgraded as well.

### CODE REVIEW

**Comment by AustinEast** [comment]
Awesome, thanks for the PR! As you can tell by the issue, its been something ive been meaning to get to 😄 glad there wasn't too much work involved.

**Comment by AustinEast** [comment]
Going to merge this in now as it seems safe enough, and probably a lot easier to find any issues if more people are trying it 👍

**Comment by superamadeus** [comment]
Thank you! I just realized that I didn't commit the updated `package-lock.json`. I'm not sure if that will cause any issues.

**Comment by AustinEast** [comment]
It won't cause any real issues as far as I'm aware, but I went ahead and updated it just now 🙂

**Pull request merged**
